on:
  push:
    branches:
      - actions-test
    paths:
      - "services/property-service/**"
      - ".github/workflows/property-service.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: |
          cd services/communications
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/property-service:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/property-service:latest